Repository GSG-CF05/Tasty-Online-Restaurant, pull requests merged in 2022-03, with the labels that each got.

#28 Add readme file
  README.md
Labels: approved

#29 upload global setting style in css files for all pages and connet htm…
  cart/cart.css
  cart/cart.html
  category/category.css
  category/category.html
  homePage/index.html
  homePage/style.css
Labels: approved

#36 create home page section by html and css
  category/category.css
  homePage/index.html
  homePage/style.css
  image/building2.jpg
Labels: awaiting review

#43 42 move index file to main folder
  index.html
Labels: approved

#47 create category section html and contains logo and background and and…
  category/category.css
  category/category.html
Labels: approved

#46 add responsive css in about section in home page
  homePage/style.css
Labels: approved

#49 upload html and css files for why choose us section relate #9
  homePage/style.css
  index.html
Labels: approved

#54 upload html , css and medai query for chef section relate #53
  homePage/style.css
  image/chef/chef1.jpg
  image/chef/chef2.jpg
  image/chef/chef3.jpg
  index.html
Labels: approved

#56 upload html , css and media query relate #10
  homePage/style.css
  index.html
Labels: approved, T1H

#66 upload css and responsive of sections in home page
  homePage/style.css
Labels: approved

#64 upload html of sections in home page
  homePage/script.js
  homePage/style.css
  image/opening-image.jpg
  index.html
Labels: awaiting review

#69 edit design
  index.html
Labels: awaiting review

#71 edit design about us
  homePage/style.css
Labels: approved

#73 add styleing for all sections
  homePage/script.js
  homePage/style.css
  index.html
Labels: awaiting review

#77 edit home section style relate #76
  homePage/style.css
  index.html
Labels: approved

#78 create category page food cards and buttons section html css and resp…
  category/category.css
  category/category.html
Labels: approved

#79 update readme file
  README.md
Labels: approved

#81 create cart page [html,ss,responsive] relates #80
  cart/cart.css
  cart/cart.html
Labels: approved

#82 update style home page
  homePage/style.css
  index.html
Labels: approved

#85 create category page js file including fething API data and saveToLoc…
  category/category.html
  category/category.js
Labels: approved

#87 86 upload js file of js
  README.md
  cart/cart.html
  cart/cart.js
Labels: approved

#89 add button in category file to return home page
  category/category.css
  category/category.html
Labels: approved

#93 upload welcome text in category page relate #92
  category/category.css
  category/category.html
  homePage/script.js
  index.html
Labels: awaiting review

#95 edit all buttons style relate #94
  cart/cart.css
  cart/cart.html
  category/category.css
  index.html
Labels: awaiting review
